Algoritmo "Aula 2.B-FUNCAO"
// 
//  
// Descrição   : TRABALHANDO COM FUNÇOES
// Autor(a)    : Danilo Sena
// Data atual  : 4/7/2023
Var
// Seção de Declarações das variáveis 
num1,num2: real

funcao dividir(a,b:real):real
inicio
retorne a/b
fimfuncao

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite o primeiro valor")
leia(num1)
escreval("Digite o segundo valor")
leia(num2)

escreval(dividir(num1,num2))

Fimalgoritmo