Algoritmo "Trabalhando com tipos de variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Data atual  : 08/06/2023
Var
// Seção de Declarações das variáveis 
nome, sobrenome, nomeCompleto: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Digite seu nome: ")
   leia(nome)
   Escreval("Digite seu sobrenome: ")
   leia(sobrenome)
   
   nomeCompleto <- nome+" "+sobrenome
   Escreval(nomeCompleto)
Fimalgoritmo