Algoritmo "Vetores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :  Marcelo
// Descrição   : Trabalhando com vetores
// Autor(a)    : Danilo
// Data atual  : 24/06/2023
Var
// Seção de Declarações das variáveis 
  vetorNomes:vetor[1..5] de caractere
  i: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para i de 1 ate 5 faca
       escreval("Digite o",i," nome: ")
       leia(vetorNomes[i])
  fimpara
       
Fimalgoritmo